# Indeed Auto-Apply Bot Configuration
# Edit these fields to customize your job search and application process


search:
  base_url: "https://au.indeed.com/jobs?q=developer&l=Sydney&sc=0kf%3Aattr%285QWDV%29%3B&radius=25"

  start: 0
  end: 20 # reduced for testing - you can increase this later

camoufox:
  user_data_dir: "user_data_dir"
  language: "au" # uk, us, fr, de, es, it, nl, pt, pl, ro, tr, ru, cn etc...





